# STREAMLIT
ALL_PROJECTS_BUTTON = 'all_projects_button'
APP = 'app'
AUDIO = 'audio'
BOT_DF_DATA = 'BOT_DF_DATA'
BOT_DF_SQL = 'BOT_DF_SQL'
BOT_DF_TITLE = 'BOT_DF_TITLE'
CKAN = 'CKAN'
COUNT_CSVS = 'count_csvs'
COUNT_DATASETS = 'count_datasets'
DASHBOARD_TAB = 'dashboard_tab'
DASHBOARD_TAB_SWITCH = 'dashboard_tab_switch'
DATAFRAME = 'dataframe'
EDITED_PACKAGES_DF = 'edited_packages_df'
HISTORY = 'history'
IMPORT = 'import'
IMPORT_OPEN_DATA_PORTAL = 'import_open_data_portal'
LAST_VOICE_MESSAGE = 'last_voice_message'
METADATA = 'metadata'
NEW_PROJECT_BUTTON = 'new_project_button'
OPEN_DATA_SOURCES = 'open_data_sources'
OPENAI_API_KEY = 'openai_api_key'
OPENAI_MODEL_NAME = 'openai_model_name'
PLOT_INDEX = 'plot_index'
PLOTS = 'plot'
PLOTLY = 'plotly'
PROJECTS = 'projects'
QUEUE = 'queue'
SCREEN_DATA = 'screen_data'
SELECT_ALL_CHECKBOXES = 'select_all_checkboxes'
SELECTED_PROJECT = 'selected_project'
SESSION_ID = 'session_id'
STR = 'str'
TABLE_INDEX = 'table_index'
TABLES = 'table'
TITLE = 'title'
UDATA = 'uData'
UPLOAD_DATA = 'upload_data'
USER_INPUT = 'user_input'
WEBSOCKET = 'websocket'
WEBSOCKET_THREAD = 'websocket_thread'

# PROPERTIES
NLP_LANGUAGE = 'nlp.language'
NLP_STT_HF_MODEL = 'nlp.speech2text.hf.model'
WEBSOCKET_PORT = 'websocket.port'

# EXTRAS
AI_ICON = '✨'

