import queue
import sys

import streamlit as st
from streamlit.runtime import Runtime
from streamlit.web import cli as stcli

from ui.bot_container import bot_container
from app.app import app
from ui.sidebar import project_selection
from ui.utils.utils import disable_input_focusout

BOT_CONTAINER_WIDTH = 0.3


def playground():
    """Show the playground container"""
    st.set_page_config(layout="wide")
    with st.sidebar:
        project_selection()
    st.title('📊 BESSER Conversational Data Analysis')
    st.subheader("🤖 Chat assistance")

    bot_col, dash_col = st.columns([BOT_CONTAINER_WIDTH, 1 - BOT_CONTAINER_WIDTH])
    if app.selected_project:
        project = app.selected_project
        if project.name not in st.session_state:
            st.session_state[project.name] = {
                'history': [],
                'queue': queue.Queue(),
                'plot': None,
                'table': None,
            }
    with bot_col:
        bot_container()
    with dash_col:
        if app.selected_project:
            tab_data, tab_plot = st.tabs(['Data', 'Plot'])

            with tab_data:
                if not st.session_state[project.name]['table']:
                    st.write(project.df)
                else:
                    st.write(st.session_state[project.name]['table'])

            with tab_plot:
                if not st.session_state[project.name]['plot']:
                    st.info(
                        'Here you can view some graphical answers generated by the bot, like line charts or histograms.',
                        icon='💡'
                    )
                else:
                    st.plotly_chart(st.session_state[project.name]['plot'], use_container_width=True)

        else:
            st.info(
                'Here is the dashboard where you can visualize the answers generated by the bot.',
                icon='💡'
            )


if __name__ == "__main__":

    if st.runtime.exists():
        playground()
        disable_input_focusout()

    else:
        sys.argv = ["streamlit", "run", sys.argv[0]]
        sys.exit(stcli.main())
